### PR TITLE
Optimise display()

### PR DESCRIPTION
**Pull request by blackening**
### Description

Fix: https://github.com/source-academy/cadet-frontend/issues/1494 

Please pick either to use the mutating yet redux breaking version (5x speedup), or the well-behaved version which copies the entire buffer every time a display is performed.

Description of bugfix:

1) Buffering and throttling the redux store updates, because every time the store is updated, entire editor is re-rendered. Rate is hardcoded to 150ms.
   * Note that for correctness, console buffer needs to be dumped before errors.
2) Mutating (push) instead of copying entire buffer at every call.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code quality improvements

### How to test

Open up playground, fire up a loop with the display function. 

Previously it would choke on 300, now it runs up to 600k on my computer. 

### Checklist

- [x] I have tested this code
- [x] I have updated the documentation

### CODE REVIEW

**Comment by martin-henz** [comment]
Great improvement! That's how a console should be. (I'm not qualified to actually review the PR.)

**Comment by martin-henz** [comment]
Looks like we have a merge conflict. Can you take a look @blackening ?

**Comment by martin-henz** [comment]
This PR isn't clear. It says "Please pick either..." but it doesn't say how to do the picking, and who is doing the picking. Can you clarify @blackening ?

**Comment by angelsl** [comment]
@martin-henz He intended for the reviewer to pick.

I will take care of this today, no worries.

**Comment by martin-henz** [comment]
> @martin-henz He intended for the reviewer to pick.
> 
> I will take care of this today, no worries.

ok

**Review by angelsl — APPROVED** [review]
Using the version that still obeys the React contract.

This yields a ~16x speedup (likely slightly more, since I did the comparison between the dev. build of this, and the current production build).

We can revisit this again in future if that is still not good enough. But I don't think it's worth the further 5x (so that would be ~80x from the baseline, but...)

**Pull request merged**
