### PR TITLE
DATA VIZ: Fix bugs, incorrect string and null displays

### PR DESCRIPTION
**Pull request by lumos309**
- Fixed `null` slash in head of pair not displaying
- Fixed wonky arrows like [this](https://sourceacademy.nus.edu.sg/playground#chap=4&ext=NONE&prgrm=MYewdgzgLgBAhjAvDAFABzgSwE4oIwA0MATAJSkDcAUACbZwDuA%2BjXFHOlrnEXORUA)
- Added quotation marks around strings (#475)
- Fixed incorrect viewport sizing for drawings with functions

### CODE REVIEW

**Comment by martin-henz** [comment]
Still not quite right: Now numbers appear as strings:

Screenshot 2019-08-18 at 12 52 57 AM

**Comment by lumos309** [comment]
> Still not quite right: Now numbers appear as strings:
> 
> Screenshot 2019-08-18 at 12 52 57 AM

Oops! Fixed now.

**Comment by geshuming** [comment]
I'm getting `Line 2: ReferenceError: is_array is not defined` from this snippet:
```
const a = (pair(1, 2));
draw_data(pair(a, a));
```

**Comment by geshuming** [comment]
Can you add the relevant functions that were removed from [this commit](https://github.com/source-academy/cadet-frontend/commit/89cb67ecb729101e4434a8126531b3217ce2390a)

**Comment by geshuming** [comment]
Some more tests I performed...

```javascript
const ebst = make_empty_tree();

const bstll = make_tree(4, ebst, ebst);
const bstlr = make_tree(5, ebst, ebst);

const bstrl = make_tree(6, ebst, ebst);
const bstrr = make_tree(7, ebst, ebst);

const bstl = make_tree(2, bstll, bstlr);
const bstr = make_tree(3, bstrl, bstrr);

const bst = make_tree(1, bstl, bstr);


draw_data(bst);
```
results in:

download2

Note the non-uniform padding of the image.

---

```javascript
const ist = list(1, "abc", x => x, pair(1,2), null, "superlongstring", 1234567890);

draw_data(ist);
```

results in:

Capture

Note the `*1` where `"superlongstring"` is supposed to be.

---

The data viz component doesn't resize together with the parent component (see below). 

Capture2

It seems like the component has a fixed window height? If the window is overflowed, it would result in 2 scroll bars!!!

image

**Comment by geshuming** [comment]
Merging due to regression issues

**Pull request merged**
