### PR TITLE
Fix for "controlBar" import reference

### PR DESCRIPTION
**Pull request by alcen**
On some systems, the script handling imports does not redirect to "controlBar/index.tsx" for imports from "/controlBar". This change is meant as a fix for that error

### CODE REVIEW

**Comment by geshuming** [comment]
Actually, why not just put the ControlBar.tsx inside the controlBar folder

**Comment by alcen** [comment]
> Actually, why not just put the ControlBar.tsx inside the controlBar folder

It's a little strange, but ControlBar.tsx does not actually use anything found inside the controlBar folder

**Comment by alcen** [comment]
How about renaming the folder to 'controlElements', and leaving ControlBar.tsx as it is? Would it be apparent that control elements are meant to be used in the control bar?

**Comment by geshuming** [comment]
in the end everything in that folder only goes into the ControlBar component, it just makes sense to group them together

**Comment by alcen** [comment]
> in the end everything in that folder only goes into the ControlBar component, it just makes sense to group them together

Ok yes, I agree. Will do this

**Comment by alcen** [comment]
> You copied the ControlBar.tsx to the folder, not moved it.

Ok, the old one is deleted now

**Pull request merged**
