### PR TITLE
Add question number to ControlBar

### PR DESCRIPTION
**Pull request by jiachen247**
Previously, when students do the missions/quizzes we have no clue how many questions the mission contains.

This makes it much easier to track progress when doing any kind of assessment.

image

### CODE REVIEW

**Comment by remo5000** [comment]
@jiachen247  Thanks for the initiative! This looks good so far, but I feel that with the inclusion of question numbers, the logic behind having previous/next/return buttons can be shifted to the ControlBar. This means that `AssessmentWorkspace` and `GradingWorkspace` only need to pass the question number and max question number, and the previous/next button logic is taken care of using the question number information inside `ControlBarProps`. Could you implement this for this PR? Do let me know if you have any doubts

**Comment by jiachen247** [comment]
yepps!!! totally agreee - cleaner this way :-)

have shifted responsibility of flow control entirely into control bar.

hope it helps!!

**Comment by remo5000** [comment]
@jiachen247 Whoops, it seems like you pushed without formatting and updating the tests -- could you run `yarn format` and `yarn test` to resolve these? I'll merge it after

**Comment by jiachen247** [comment]
@remo5000 great! have formatted the code and have updated the failing snapshots :-)

**Comment by remo5000** [comment]
@jiachen247 Merged, cheers!

**Comment by jiachen247** [comment]
@remo5000 when will the changes go live? haha

**Comment by remo5000** [comment]
@jiachen247 We're going to be deploying v1.0.9 soon 🤞

**Comment by jiachen247** [comment]
@remo5000 sounds good man! looking forward to it. thanks for all the hard work!! its an amazing platform :-)

**Pull request merged**
