### PR TITLE
Add List Visualiser

### PR DESCRIPTION
**Pull request by remo5000**
### Requirements
- [x] js-slang must specify the `draw` function to be available (not exactly necessary, but is essential for testing)

### Features
- calling `draw` on a list visualises it in a side content tab
- The visualiser is only available on the playground
- The "Next", "Previous" and "Clear" buttons have been scrapped, as that introduces a two-way interaction between the application (that calls the external functions) and the library (that manipulates the dom and refers to the buttons by class and id). Either ways, I don't see the use case for visualising multiple lists in quick succession.

### CODE REVIEW

**Comment by ningyuansg** [comment]
Are changes to MCQ meant to be part of this PR or included by accident?

**Comment by remo5000** [comment]
It's by accident, those changes should have showed up from #263

**Comment by remo5000** [comment]
Rebased to the squash-commit of #263

**Comment by ningyuansg** [comment]
Please resolve https://github.com/source-academy/js-slang/pull/27 and publish before this branch is merged.

**Comment by remo5000** [comment]
@ningyuansg Bumped!

**Pull request merged**
