### PR TITLE
Default texts for data visualiser, inspector, env visualiser

### PR DESCRIPTION
**Pull request by alcen**
In this commit, there are now default texts shown for Data Visualiser, Inspector and Env Visualiser. This text disappears when the respective components are used for the first time

These default texts would resolve issue #283

A screenshot of what happens when 'Data Visualizer' is selected in the Playground:

data-viz-default-text

Note: this pull request was previously split from #808. You may view the comments history related to this pull request there

### CODE REVIEW

**Comment by alcen** [comment]
> I was wondering if we can keep the default text even when the component is being used.

We can, but I don't think there is a need to? It will only crowd the interface

**Comment by martin-henz** [comment]
> > I was wondering if we can keep the default text even when the component is being used.
> 
> We can, but I don't think there is a need to? It will only crowd the interface

Yes, the text has useful info, but I agree with @alcen : It would take up screen space and would add the need to scroll frequently. At the moment, it's nicely satisfying the curiosity of the user who clicks around to see what's there.

**Comment by martin-henz** [comment]
@alcen can you look at the conflicts?

**Comment by alcen** [comment]
> @alcen can you look at the conflicts?

Ok, seems like this has resolved it!

**Pull request merged**
