### PR TITLE
Clean up package.json

### PR DESCRIPTION
**Pull request by geshuming**
Removed a bunch of unused dependencies, and bumping js-slang to 0.2.2.

I don't really have a clue what to do with the scripts though. @rrtheonlyone would you like to check them out?

Part of #608

### CODE REVIEW

**Comment by geshuming** [comment]
The coverage fix script seems like it is supposed to stash `*.d.ts` files and unstash them. I don't think this script is needed at all

**Comment by martin-henz** [comment]
Not sure about the status of this issue. Is it worth resolving the conflicts?

**Comment by martin-henz** [comment]
@alcen : any views on this? Should we try to see if there is anything useful in this PR?

**Comment by alcen** [comment]
> 
> 
> @alcen : any views on this? Should we try to see if there is anything useful in this PR?

I think that the branch is too outdated already. Probably better to re-make these changes on the current master instead

**Comment by martin-henz** [comment]
> > @alcen : any views on this? Should we try to see if there is anything useful in this PR?
> 
> I think that the branch is too outdated already. Probably better to re-make these changes on the current master instead

OK. Can you see what you can recover from this PR and put it in a fresh one?

**Pull request closed without merging**
