### PR TITLE
Add 3D renders and make_3D_color_point

### PR DESCRIPTION
**Pull request by yongxiangng**
### Description

Added 3D renders. These functions are similar with those of 2D curves and we are working to update the documentation for the 3D renders. (we are still working on `draw_3D_connected_full_view`)

- `draw_3D_connected`
- `draw_3D_connected_full_view_proportional`
- `draw_3D_connected_squeezed_to_window`
- `draw_3D_points_on`
- `draw_3D_points_squeezed_to_window`

Added 3D color points. Takes in x, y, z, r, g, b and returns a point in 3D with color r, g, b.
- `make_3D_color_point`

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Code quality improvements

### How to test

- Run instance of cadet-frontend, and navigate to playground
- Include CURVES library

To test `make_3D_color_point`
```

const curve = t => make_3D_color_point(
    0.5,                                    //x-coordinate
    0.5*math_sin(math_PI*t)+0.5,            //y-coordinate
    t,                                      //z-coordinate
    math_pow(math_cos(2*math_PI*t), 2)*255, //r-component
    math_pow(math_sin(2*math_PI*t), 2)*255, //g-component
    t*255);                                 //b-component
draw_3D_connected(1000)(curve);
```

For the 3D renders, here are some test curves

```
const curve1 = t => make_color_point(
    0.5*math_cos(2*math_PI*t)+0.5,          //x-coordinate
    0.8*math_sin(2*math_PI*t)+0.5,          //y-coordinate
    5,                                    //r-coordinate
    5,                                    //g-component
    5);                                   //b-component
    
const curve2 = t => make_3D_color_point(
    0.5,                                    //x-coordinate
    0.5*math_sin(math_PI*t)+0.5,            //y-coordinate
    t,                                      //z-coordinate
    math_pow(math_cos(2*math_PI*t), 2)*255, //r-component
    math_pow(math_sin(2*math_PI*t), 2)*255, //g-component
    t*255);                                 //b-component
    
const curve3 = t => make_3D_color_point(
    -0.5*math_sin(math_PI*t)+0.5,           //x-coordinate
    0.5,                                    //y-coordinate
    t,                                      //z-coordinate
    math_pow(math_sin(2*math_PI*t), 2)*255, //r-component
    math_pow(math_cos(2*math_PI*t), 2)*255, //g-component
    t*255);                                 //b-component
    
const curve4 = t => make_3D_color_point(
    0.5*math_sin(math_PI*t)+0.5,            //x-coordinate
    0.5,                                    //y-coordinate
    t,                                      //z-coordinate
    math_pow(math_sin(2*math_PI*t), 2)*255, //r-component
    math_pow(math_cos(2*math_PI*t), 2)*255, //g-component
    t*255);                                 //b-component
    
const curve5 = t => make_3D_color_point(
    0.5,                                    //x-coordinate
    -0.5*math_sin(math_PI*t)+0.5,         //y-coordinate
    t,                                      //z-coordinate
    math_pow(math_cos(2*math_PI*t), 2)*255, //r-component
    math_pow(math_sin(2*math_PI*t), 2)*255, //g-component
    t*255);                                 //b-component
```

To test `draw_3D_connected`

```
draw_3D_connected(1000)(connect_rigidly(curve1, 
connect_rigidly(connect_rigidly(curve3, curve2),
connect_rigidly(curve4, curve5))));
```

To test `draw_3D_connected_full_view_proportional`

```
draw_3D_connected_full_view_proportional(1000)(connect_rigidly(curve1, 
connect_rigidly(connect_rigidly(curve3, curve2),
connect_rigidly(curve4, curve5))));
```
To test `draw_3D_connected_squeezed_to_window`

```
draw_3D_connected_squeezed_to_window(1000)(connect_rigidly(curve1, 
connect_rigidly(connect_rigidly(curve3, curve2),
connect_rigidly(curve4, curve5))));
```

To test `draw_3D_points_on`

```
draw_3D_points_on(1000)(connect_rigidly(curve1, 
connect_rigidly(connect_rigidly(curve3, curve2),
connect_rigidly(curve4, curve5))));
```

To test `draw_3D_points_squeezed_to_window`

```
draw_3D_points_squeezed_to_window(1000)(connect_rigidly(curve1, 
connect_rigidly(connect_rigidly(curve3, curve2),
connect_rigidly(curve4, curve5))));
```

Do also check that `connect_rigidly` works with 3D and color curves.

Here are some other curves which could aid in testing.

```
let curve = t => make_3D_point(0.3*math_sin(2*math_PI*t) + 0.5,
    0.3*math_cos(2*math_PI*t) + 0.5,
    t);    
let curve = t => make_3D_point(0.3*math_tan(2*math_PI*t) + 0.5,
    0.3*math_cos(2*math_PI*t) + 0.5,
    t);    
let curve = t => make_3D_point(0.3*math_tan(2*math_PI*t) + 0.5,
    0.3*math_tan(2*math_PI*t) + 0.5,
    t);    
```

### Checklist

- [x] I have tested this code
- [ ] I have updated the documentation

### CODE REVIEW

**Review by shermanyuen — COMMENTED** [review]
I will be using the following curves in my review:
```
const curve1 = t => make_3D_color_point(t, 0, math_pow(t, 2), 1/0, -1/0, 3*256*t - 256);
const curve2 = t => make_3D_point(t, 0, math_pow(2*t, 2));
const curve3 = t => make_3D_point(t, 0, math_pow(2*t, 50));
const curve4 = t => make_3D_point(t, 0, math_pow(2*t, 1500));
const curve5 = t => make_3D_point(t, 0.2*t - 0.1, math_pow(t, 2));
const curve6 = t => make_3D_point(0.5, 0.5, t);
```

`make_3D_color_point`:
- Invalid color values are naturally handled, e.g., see `draw_3D_connected(1000)(curve1)`. Good job!

`draw_3D_connected`:
- It is assumed that the x-axis goes from left to right, y-axis from front to back, and z-axis from bottom to top. Could this be made more explicit? For example, each axis could be labelled
- When the numbers are too large, the curve fades between adjacent points, e.g., see `draw_3D_connected(1000)(curve4)`: the curve at (0.5, 0, 1) fades out of the cube; contrast this with `draw_3D_connected(1000)(curve3)`.

`draw_3D_connected_full_view_proportional`:
- My understanding of this function is that each axis is scaled independently to [0, 1] and the curve centralized such that the whole curve lies within the cube, and then some padding is added within the cube. However it seems like the curve is just translated to the median and the scaling remains invariant. For example:
    - `draw_3D_connected_full_view_proportional(1000)(curve5)`: the y-axis is not scaled from [-0.1, 0.1] to [0, 1], but rather from [-0.1, 0.1] to [0.4, 0.6].
    - `draw_3D_connected_full_view_proportional(1000)(curve2)`: only the middle portion of the curve is shown.
- When the numbers are too large, the cube and the curve are not seen, e.g., `draw_3D_connected_full_view_proportional(1000)(curve4)`; contrast this with `draw_3D_connected_full_view_proportional(1000)(curve3)`.
- Semantics: Is there a reason to include the padding? E.g., compare `draw_3D_connected_full_view_proportional(1000)(curve6)` with `draw_3D_connected(1000)(curve6)`: the former has some parts cut off at the start and at the end.

`draw_3D_connected_squeezed_to_window`:
- My understanding of this function is that every axis is scaled by the same amount and the curve centralized such that the whole curve lies within the cube. However, it seems like the curve is just translated to the median and the scaling remains invariant. For example:
    - `draw_3D_connected_squeezed_to_window(1000)(curve5)`: the y-axis is not scaled from [-0.1, 0.1] to [0, 1], but rather from [-0.1, 0.1] to [0.4, 0.6].
    - `draw_3D_connected_squeezed_to_window(1000)(curve2)`: only the middle portion of the curve is shown.
- The result looks like `draw_3D_connected_full_view_proportional` except without padding.

`draw_3D_points_on`:
- Looks good!

`draw_3D_points_squeezed_to_window`:
- Same comments as `draw_3D_connected_squeezed_to_window`.

**Comment by zhenghanlee** [comment]
> I will be using the following curves in my review:
> 
> ```
> const curve1 = t => make_3D_color_point(t, 0, math_pow(t, 2), 1/0, -1/0, 3*256*t - 256);
> const curve2 = t => make_3D_point(t, 0, math_pow(2*t, 2));
> const curve3 = t => make_3D_point(t, 0, math_pow(2*t, 50));
> const curve4 = t => make_3D_point(t, 0, math_pow(2*t, 1500));
> const curve5 = t => make_3D_point(t, 0.2*t - 0.1, math_pow(t, 2));
> const curve6 = t => make_3D_point(0.5, 0.5, t);
> ```
> 
> `make_3D_color_point`:
> 
> * Invalid color values are naturally handled, e.g., see `draw_3D_connected(1000)(curve1)`. Good job!
> 
> `draw_3D_connected`:
> 
> * It is assumed that the x-axis goes from left to right, y-axis from front to back, and z-axis from bottom to top. Could this be made more explicit? For example, each axis could be labelled.
> * When the numbers are too large, the curve fades between adjacent points, e.g., see `draw_3D_connected(1000)(curve4)`: the curve at (0.5, 0, 1) fades out of the cube; contrast this with `draw_3D_connected(1000)(curve3)`.
> 
> `draw_3D_connected_full_view_proportional`:
> 
> * My understanding of this function is that each axis is scaled independently to [0, 1] and the curve centralized such that the whole curve lies within the cube, and then some padding is added within the cube. However it seems like the curve is just translated to the median and the scaling remains invariant. For example:
>   
>   * `draw_3D_connected_full_view_proportional(1000)(curve5)`: the y-axis is not scaled from [-0.1, 0.1] to [0, 1], but rather from [-0.1, 0.1] to [0.4, 0.6].
>   * `draw_3D_connected_full_view_proportional(1000)(curve2)`: only the middle portion of the curve is shown.
> * When the numbers are too large, the cube and the curve are not seen, e.g., `draw_3D_connected_full_view_proportional(1000)(curve4)`; contrast this with `draw_3D_connected_full_view_proportional(1000)(curve3)`.
> * Semantics: Is there a reason to include the padding? E.g., compare `draw_3D_connected_full_view_proportional(1000)(curve6)` with `draw_3D_connected(1000)(curve6)`: the former has some parts cut off at the start and at the end.
> 
> `draw_3D_connected_squeezed_to_window`:
> 
> * My understanding of this function is that every axis is scaled by the same amount and the curve centralized such that the whole curve lies within the cube. However, it seems like the curve is just translated to the median and the scaling remains invariant. For example:
>   
>   * `draw_3D_connected_squeezed_to_window(1000)(curve5)`: the y-axis is not scaled from [-0.1, 0.1] to [0, 1], but rather from [-0.1, 0.1] to [0.4, 0.6].
>   * `draw_3D_connected_squeezed_to_window(1000)(curve2)`: only the middle portion of the curve is shown.
> * The result looks like `draw_3D_connected_full_view_proportional` except without padding.
> 
> `draw_3D_points_on`:
> 
> * Looks good!
> 
> `draw_3D_points_squeezed_to_window`:
> 
> * Same comments as `draw_3D_connected_squeezed_to_window`.

`draw_3D_connected`:
* Thanks for the suggestion. We are keeping that in mind and will see if we can implement that in our future PR.
* We are looking into the problem right now.

`draw_3D_connected_full_view_proportional`:
*  By 'proportional' we mean every axis to be scaled by the same amount - the proportions remains the same.
  * If `curve5`'s size on y-axis : x-axis = 0.2 : 1, it should remain so in the cube.
  * Similarly, if `curve2`'s size on x-axis : z-axis = 1 : 4, it should remain so in the cube.
* Same as per second comment under `draw_3D_connected`.
* We included padding as we built our 3D rendering functions analogous to its 2D counterparts. However, we understand your concern. Since the cube already has a padding around it, we will discuss with professor in the next meeting and see if we could remove `draw_3D_points_squeezed_to_window` and subsequently remove padding in `draw_3D_connected_full_view_proportional` by our next PR when we implement `draw_3D_connected_full_view`.

`draw_3D_connected_squeezed_to_window`:
* Same comment as per `draw_3D_connected_full_view_proportional`.
* That was the intention of having it 'squeezed to window'.

**Comment by zhenghanlee** [comment]
> I will be using the following curves in my review:
> 
> ```
> const curve1 = t => make_3D_color_point(t, 0, math_pow(t, 2), 1/0, -1/0, 3*256*t - 256);
> const curve2 = t => make_3D_point(t, 0, math_pow(2*t, 2));
> const curve3 = t => make_3D_point(t, 0, math_pow(2*t, 50));
> const curve4 = t => make_3D_point(t, 0, math_pow(2*t, 1500));
> const curve5 = t => make_3D_point(t, 0.2*t - 0.1, math_pow(t, 2));
> const curve6 = t => make_3D_point(0.5, 0.5, t);
> ```
> 
> `draw_3D_connected`:
> 
> * It is assumed that the x-axis goes from left to right, y-axis from front to back, and z-axis from bottom to top. Could this be made more explicit? For example, each axis could be labelled.
> * When the numbers are too large, the curve fades between adjacent points, e.g., see `draw_3D_connected(1000)(curve4)`: the curve at (0.5, 0, 1) fades out of the cube; contrast this with `draw_3D_connected(1000)(curve3)`.

Regarding the curve fading out of the cube, the problem was caused by us setting points outside the cube but within clip space to white. There were a few proposals on how we wanted to deal with points outside the cube:
* Setting the color of points outside the cube to white, problems include:
    * Causes fading if points lie within the clip space.
    * Nothing renders in between two adjacent points that lie just outside cube.
* Setting the coordinates of the points that lie outside the cube to the edge of the cube, problems include:
    * If we just take the output of applying the function of the curve to x, y, z = 0 or 1 (the edges), it may not reflect accurately on where the line that connects the two points actually intersects the axes.
    * If the curve makes a loop outside the cube and returns into the cube, the point will be connected to where it left off the cube.
* Drawing white triangles outside the cube to cover up anything that is outside the cube, problems include:
    * Not being able to cover all sides of the cube in a perspective view.
    * Not feasible when we want to implement perspective control/cube rotation in the future
* Remove the clip function (see latest commit on origin/sa2122-graphics) and allow the curve to render outside the cube.
The team has discussed and thinks that the last solution may be the best for now, and updated the PR accordingly. We will have to updated on the function's specifications in js-slang's documentation thereafter.

**Review by shermanyuen — APPROVED** [review]
Nil

**Pull request merged**
