### PR TITLE
CP3108 Staff Dashboard - Assessment Uploader

### PR DESCRIPTION
**Pull request by Wong-ZZ**
## Context
This PR adds the Assessment Uploader component for the CP3108 Staff Dashboard project. The Assessment Uploader, also called the GroundControl, provides an interface for staff to manage assessments for the course. Staff can upload, delete, publish or update assessments through this interface.

## Implementation
+ The GroundControl is accessible through the GroundControl tab in the navigation bar and can only be accessed by staffs/admin.
+ Added various request methods to aid with the uploading, deleting, publishing and updating of assessments.
+ Added an optional field, isPublished to IAssessmentOverview.
+ Added @blueprintjs/datetime for the date input for changing an assessment's open/close dates.

The UI for GroundControl can be seen here:
aaaa

## Other Information
Corresponding PR to `cadet`: [PR 586](https://github.com/source-academy/cadet/pull/586)
More info in the wiki: [Assessment Uploader](https://github.com/source-academy/cadet-frontend/wiki/Staff-Dashboard#assessment-uploader)

### CODE REVIEW

**Comment by Wong-ZZ** [comment]
I couldn't recreate the error which you encountered but I did find a bug that occurs when deleting an assessment and I'm not sure if it is related to the error you are facing.

Can you try pulling from my latest commit from the backend PR and see if you still face the same error. Also can you display the browser console when deleting the assessment so that I can see the response from the backend? Thanks a lot.

**Comment by Wong-ZZ** [comment]
I just remembered that the nginx config file from the cadet repo does not allow for DELETE requests which causes you to get logged out when deleting an assessment.

[nginx.conf.txt](https://github.com/source-academy/cadet-frontend/files/4532393/nginx.conf.txt)
Try using this config for nginx instead

**Comment by sun-yitao** [comment]
> I just remembered that the nginx config file from the cadet repo does not allow for DELETE requests which causes you to get logged out when deleting an assessment.
> 
> [nginx.conf.txt](https://github.com/source-academy/cadet-frontend/files/4532393/nginx.conf.txt)
> Try using this config for nginx instead

Thanks for pointing that out. I used the nginx config provided and now it no longer logs me out but it seems to be something to do with the backend instead:
Screenshot 2020-04-26 at 3 27 10 PM

```
[info] DELETE /v1/assessments/3
[debug] Processing with CadetWeb.AssessmentsController.delete/2
  Parameters: %{"id" => "3"}
  Pipelines: [:api, :auth, :ensure_auth]
[debug] QUERY OK source="users" db=0.3ms
SELECT u0."id", u0."name", u0."role", u0."nusnet_id", u0."group_id", u0."inserted_at", u0."updated_at" FROM "users" AS u0 WHERE (u0."id" = $1) [10]
[debug] QUERY OK source="assessments" db=0.3ms
SELECT a0."id", a0."title", a0."is_published", a0."type", a0."summary_short", a0."summary_long", a0."open_at", a0."close_at", a0."cover_picture", a0."mission_pdf", a0."number", a0."story", a0."reading", a0."password", a0."inserted_at", a0."updated_at" FROM "assessments" AS a0 WHERE (a0."id" = $1) [3]
[debug] QUERY ERROR source="submissions" db=0.6ms queue=0.2ms
DELETE FROM "submissions" AS s0 WHERE (s0."assessment_id" = $1) [3]
[info] Sent 500 in 14ms
[error] #PID<0.675.0> running CadetWeb.Endpoint (connection #PID<0.674.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: DELETE /v1/assessments/3
** (exit) an exception was raised:
    ** (Postgrex.Error) ERROR 23503 (foreign_key_violation) update or delete on table "submissions" violates foreign key constraint "answers_submission_id_fkey" on table "answers"

    table: answers
    constraint: answers_submission_id_fkey

Key (id)=(5) is still referenced from table "answers".
        (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto_sql) lib/ecto/adapters/sql.ex:554: Ecto.Adapters.SQL.execute/5
        (cadet) lib/cadet/assessments/assessments.ex:67: Cadet.Assessments.delete_assessment/2
        (cadet) lib/cadet_web/controllers/assessments_controller.ex:77: CadetWeb.AssessmentsController.delete/2
        (cadet) lib/cadet_web/controllers/assessments_controller.ex:1: CadetWeb.AssessmentsController.action/2
        (cadet) lib/cadet_web/controllers/assessments_controller.ex:1: CadetWeb.AssessmentsController.phoenix_controller_pipeline/2
        (phoenix) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (cadet) lib/plug/error_handler.ex:64: CadetWeb.Router.call/2
        (cadet) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint.plug_builder_call/2
        (cadet) lib/plug/debugger.ex:122: CadetWeb.Endpoint."call (overridable 3)"/2
        (cadet) lib/cadet_web/endpoint.ex:1: CadetWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:42: 
```

**Comment by Wong-ZZ** [comment]
You have to pull from the latest commit I made to the backend PR a few days ago that fixed this specific bug

**Comment by sun-yitao** [comment]
> You have to pull from the latest commit I made to the backend PR a few days ago that fixed this specific bug

Oh yes the latest commit works now, thanks!

**Comment by seanlowjk** [comment]
Do let me know if you would want to fix the merge conflicts yourself thanks =)

**Comment by angelsl** [comment]
#1058, which contained some or all of the commits from this PR, was merged.

So.. I'm not sure if this needs to be merged anymore.

**Pull request closed without merging**
