### PR TITLE
Disable MCQ selection in Grading workspace

### PR DESCRIPTION
**Pull request by remo5000**
### Features
- Buttons are clickable (to show hints), but the option does not get highlighted.
- An optional prop is used (like in ControlBar) as it is not an expected default behaviour

### CODE REVIEW

**Comment by ningyuansg** [comment]
Good enhancement, but may as well use tooltips onhover to show hints, and just disable all the buttons.

**Comment by remo5000** [comment]
Good idea, I'll add that in later.

**Comment by ningyuansg** [comment]
Good comment, noted with thanks.

**Comment by remo5000** [comment]
I just tried it out. I think the way `hint` is used makes it better off as a notification. For example,

image

We would want the student to see the explanation for why the answer is correct, only after clicking it.

**Comment by ningyuansg** [comment]
I meant in the context of the grading workspace, that graders are able to view hints by hovering over the choice. No changes to student's view.

**Comment by remo5000** [comment]
Don't think I have time to work on this for now, will reopen if I do though. The main pain point is creating a behaviour duality within the `MCQChooser`.

**Pull request closed without merging**
