### PR TITLE
Bump js-slang

### PR DESCRIPTION
**Pull request by openorclose**
https://github.com/source-academy/js-slang/pull/362

### CODE REVIEW

**Comment by martin-henz** [comment]
Is merge deployed already? 

I'm asking because I might want to squeeze in a change in the parse function of Source §4, if you could wait a while.

**Comment by openorclose** [comment]
> Is merge deployed already?
> 
> I'm asking because I might want to squeeze in a change in the parse function of Source §4, if you could wait a while.

Yeah I don't think there's a deploy yet

**Comment by martin-henz** [comment]
OK. Want to check with you: I don't like the verbosity of the output of the parse function. It has all this debugging info: line and position numbers, which distract the students and which add clutter. In the course we don't use this info. It's of course needed for any serious work, but I think that would go beyond the purpose of this module. So I'm thinking of cutting out all that stuff from the parser. Any views?

**Comment by openorclose** [comment]
> OK. Want to check with you: I don't like the verbosity of the output of the parse function. It has all this debugging info: line and position numbers, which distract the students and which add clutter. In the course we don't use this info. It's of course needed for any serious work, but I think that would go beyond the purpose of this module. So I'm thinking of cutting out all that stuff from the parser. Any views?

Yeah that sounds good, we can have `parse` that doesn't have the line and location, and `parse_verbose` that works like how the current `parse` works.

**Comment by martin-henz** [comment]
That's a good idea! Can you set that up? Would save me a lot of time!

**Pull request merged**
