### PR TITLE
Substitution model visualizer

### PR DESCRIPTION
**Pull request by LeowWB**

### CODE REVIEW

**Comment by geshuming** [comment]
Please don't commit package-lock here. Delete the changes on package-lock, and run `npm ci` to ensure you only install the dependencies on the package lock.

**Comment by geshuming** [comment]
Please fix the tests. Make sure travis pass, do not push changes with --no-verify flag@alcen

**Comment by geshuming** [comment]
If possible, rebase the PR so we only see required changes

**Comment by alcen** [comment]
> Please fix the tests. Make sure travis pass, do not push changes with --no-verify flag @alcen

Don't worry, I am not using --no-verify to push. Travis fails because this branch does not work with the current js-slang. 

This change here will need to be put in --> https://github.com/source-academy/js-slang/pull/320

**Comment by geshuming** [comment]
Then we'll wait until we get js-slang updated

**Comment by geshuming** [comment]
Can I get some screenshots in the meantime?

**Comment by alcen** [comment]
> Can I get some screenshots in the meantime?

No problem. Here they are:
&nbsp;
Default text of the Substituter tab
&nbsp;
photo6222269970012809593Substituter can be run by being on the Substituter tab, using Source §2 and below, and hitting "Run"
&nbsp;
It can also be activated by setting breakpoints on Source §2 and below. Ideally the program would run until the breakpoint is reached, however the position of the breakpoint currently has no consequence because the functionality is not yet implemented in js-slang.

**Comment by martin-henz** [comment]
> > Can I get some screenshots in the meantime?
> 
> No problem. Here they are:
>  
> Default text of the Substituter tab
>  
> photo6222269970012809593Substituter can be run by being on the Substituter tab, using Source §2 and below, and hitting "Run"
>  
> It can also be activated by setting breakpoints on Source §2 and below. Ideally the program would run until the breakpoint is reached, however the position of the breakpoint currently has no consequence because the functionality is not yet implemented in js-slang.

expmod is quite a nasty example. These expression blocks will not appear if we only write functions whose body starts with "return".

Having said that: the substituter covers all of Source §2, and the handling of function calls whose body does not start with "return" is quite straightforward and I hope won't cause issues with the students.

**Pull request merged**
